model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"
approval_policy = "on-request"
web_search_request = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[tui]
notifications = [ "agent-turn-complete", "approval-requested" ]

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[projects."/Users/yuichi"]
trust_level = "untrusted"
